### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by mikesamuel** [mini-lang/mini-lang#2]
There is a broken link in https://github.com/mini-lang/mini-lang#5-improve-the-article-series-

> If you are a writer and want to contribute to the article series, please see the \[contributing to the article series\]\(https://github.com/mini-lang/mini-lang/blob/main/CONTRIBUTING#Article-series) section.

Perhaps there should be a `.md` after `CONTRIBUTING`.

**Comment by WilliamRagstad** [comment]
Yes indeed! Nicely catched
